name = "rala-search"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV Namespace binding
[[kv_namespaces]]
binding = "DICTIONARY"
id = "3c0a155119644621bd656231b4ec9063"

# Note: CPU limits are not available on Free plan
# [limits]
# cpu_ms = 50

